apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timeserver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: timeserver
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/timeserver
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - DeleteNamespace=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/instance: timeserver
    automated:
      selfHeal: true
      prune: true
